========================================================================================================================

Milestone 3

    Nama  : Badriah Nursakinah
    Batch : FTDS-005-RBSD

    This program aims to validate the dataset through testing whether it meets the Seventh Expectation of:
- to be unique
- to be between min_value and max_value
- to be in set (rating,low,medium,high)
- to be in type list 
- to be calculate total amount
- to be Contain
- to be Missing Value



========================================================================================================================

great expectation adalah memproses validasi data,,,

### 1. Install Great Expectation Package

In [1]:
# Install the library if you do not have it

! pip install -q great-expectations

install -q great-expectations sucsess

### 2. Instantiate Data Context

In [2]:
# Create a data context

from great_expectations.data_context import FileDataContext

context = FileDataContext.create(project_root_dir='./')

### 3. Connect to A `Datasource`

In [4]:
# Give a name to a Datasource. This name must be unique between Datasources.
datasource_name = 'video_game_sales_datasource'
datasource = context.sources.add_pandas(datasource_name)

# Give a name to a data asset
asset_name = 'Video Game Sales Report'
path_to_data = 'P2M3_badriahnursakinah_data_clean.csv'
asset = datasource.add_csv_asset(asset_name, filepath_or_buffer=path_to_data)

# Build batch request
batch_request = asset.build_batch_request()

In [5]:
# Creat an expectation suite
expectation_suite_name = 'expectation-trip-dataset'
context.add_or_update_expectation_suite(expectation_suite_name)

# Create a validator using above expectation suite
validator = context.get_validator(
    batch_request = batch_request,
    expectation_suite_name = expectation_suite_name
)

# Check the validator
validator.head()

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

rank                      name platform    year         genre publisher  \
0    1                Wii Sports      Wii  2006.0        Sports  Nintendo   
1    2         Super Mario Bros.      NES  1985.0      Platform  Nintendo   
2    3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3    4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4    5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

   na_sales  eu_sales  jp_sales  other_sales  global_sales  
0     41.49     29.02      3.77         8.46         82.74  
1     29.08      3.58      6.81         0.77         40.24  
2     15.85     12.88      3.79         3.31         35.82  
3     15.75     11.01      3.28         2.96         33.00  
4     11.27      8.89     10.22         1.00         31.37

Displays success data

### 4. Create an Expectation Suite

-  ### A. Expectation `to be unique` pada pada kolom Video Game Sales Report

In [10]:
# Expectation 1 : Column `rank` must be unique

validator.expect_column_values_to_be_unique('rank')

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 16599,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

Insight for the result :Based on the results displayed, it can be concluded that:

Element Count: There are 16599 elements or rows in the data.
Unexpected Count: There are no unexpected values ​​in the data.
Unexpected Percent: 0% of the values ​​in the data are unexpected values.
Partial Unexpected List: There is no list of unexpected values.
Missing Count: There are no missing or missing values ​​in the data.
Missing Percent: 0% of the values ​​in the data are missing values.
Unexpected Percent Total: 0% of the total values ​​in the data are unexpected values.
Unexpected Percent Non-missing: 0% of the non-missing values ​​in the data are unexpected values.

So, based on the analysis above, it can be concluded that the data does not have unexpected or missing values, and all values ​​in the rank column are unique, according to the expectations set in the code



The reason for using the expectation to be unique in the 'rank' column, we can ensure that the video_game_sales_datasource dataset has good data integrity, accurate analysis, effective anomaly detection, and consistency with applicable business scenarios

 - ### B. Expectation `to be between min_value and max_value` pada kolom Video Game Sales Report

In [25]:
# Expectation 2 : Column `global_sales` must be less than $ 0.0 million

validator.expect_column_values_to_be_between(
    column='global_sales', min_value=0, max_value=82.74
)

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 16599,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

Insight for the result From the results displayed, it can be concluded that:

Element Count: There are 16599 elements or rows in the data.
Unexpected Count: There are no unexpected values ​​in the data.
Unexpected Percent: 0% of the values ​​in the data are unexpected values.
Partial Unexpected List: There is no list of unexpected values.
Missing Count: There are no missing or missing values ​​in the data.
Missing Percent: 0% of the values ​​in the data are missing values.
Unexpected Percent Total: 0% of the total values ​​in the data are unexpected values.
Unexpected Percent Non-missing: 0% of the non-missing values ​​in the data are unexpected values. It can be said that all values ​​in the global_sales column are in line with expectations, namely less than $82.74 million.



Reasons for using By using the expectation to be between min_value and max_value in the 'global_sales' column, it can be used as a preprocessing or data validation step

- ### C. Expectation `to be in set` pada kolom Video Game Sales Report

In [26]:
# Expectation 3 : Column `genre` must contain

validator.expect_column_values_to_be_in_set('platform', ['Wii','NES','GB','DS','X360','PS3','PS2','SNES','GBA', '3DS','PS4','N64','PS','XB','PC','2600','PSP','XOne','GC', 'WiiU', 'GEN','DC','PSV','SAT','SCD', 'WS', 'NG', 'TG16', '3DO', 'GG', 'PCFX'])

# genre = salah
# platform = salah

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": false,
  "result": {
    "element_count": 16599,
    "unexpected_count": 1,
    "unexpected_percent": 0.006024459304777396,
    "partial_unexpected_list": [
      "0"
    ],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.006024459304777396,
    "unexpected_percent_nonmissing": 0.006024459304777396
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

Insight for the result From the results displayed, it can be concluded that: It is necessary to carry out further checks and analysis to find out the reason for the value "0" in the platform column which does not match expectations.

The reason for using Expectation `to be in set` in the platform column is to ensure consistency in platform naming. For example, ensuring there is no spelling difference between "Playstation" and "PS"

### D. Expectation `to be in type` pada kolom Video Game Sales Report

In [16]:
# Expectation 4 : Column `na_sales` must in form of integer or float (Sales in North America (in millions))

validator.expect_column_values_to_be_in_type_list('na_sales', ['int64', 'float'])

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "observed_value": "float64"
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

Insight for the result From the results displayed, it can be concluded that:

Observed Value: The data type of the na_sales column is float64.
Based on these results, it can be seen that the expectations set in the code
validator.expect_column_values_to_be_in_type_list('na_sales', ['int64', 'float']) has been met.

This means:

The na_sales column contains values ​​in integer or float form, as expected.
There are no values ​​in the na_sales column that deviate from the integer or float data type.
So, it can be concluded that the na_sales column has met the specified expectations, namely containing values ​​in integer or float form.



The reason for using Expectation `to be in type` in the 'na_sales' column which stores sales data in the North American,  markets which have numeric data types (such as float or decimal) so that they can be used correctly in analysis and calculations

### E. Expectation `calculate total amount` pada kolom Video Game Sales Report

In [17]:
# Expectation 5 : Column `jp_sales` must be exist to calculate Sales in Japan (in millions)
validator.expect_column_to_exist(column='jp_sales')

Calculating Metrics:   0%|          | 0/2 [00:00<?, ?it/s]

{
  "success": true,
  "result": {},
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

Insight for the result  From the results displayed, it can be concluded that:

Success: The expectation specified in the code validator.expect_column_to_exist(column='jp_sales') has been met.
This means:

The jp_sales column exists and is present in the dataset.
There are no problems or errors regarding the existence of the jp_sales column.
So, it can be concluded that the jp_sales column already exists and is available in the dataset, so it can be used to calculate sales in Japan (in millions) according to expectations.



The reason for using Expectation `calculate total amount` in the jp_sales column is to validate the completeness of the data by calculating total sales in the Japanese market

### F. Expectation `Contain` pada kolom Video Game Sales Report

In [22]:
validator.expect_column_values_to_be_in_set('platform', ['Wii', 'NES', 'GB', 'DS', 'X360', 'PS3',
       'PS2', 'SNES', 'GBA', '3DS', 'PS4', 'N64',
       'PS', 'XB', 'PC', '2600', 'PSP', 'XOne',
       'GC', 'WiiU', 'GEN', 'DC', 'PSV', 'SAT',
       'SCD', 'WS', 'NG', 'TG16', '3DO', 'GG', 'PCFX'])

       # genre = false
       # publisher = false

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": false,
  "result": {
    "element_count": 16599,
    "unexpected_count": 1,
    "unexpected_percent": 0.006024459304777396,
    "partial_unexpected_list": [
      "0"
    ],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.006024459304777396,
    "unexpected_percent_nonmissing": 0.006024459304777396
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

Insight for the result based on the results displayed, the following insights can be provided:

Success: The expectation set in the code validator.expect_column_values_to_be_in_set('platform', [...]) was not met.
Unexpected Count: There is 1 value that does not match expectations.
Unexpected Percent: Values ​​that do not match expectations are only 0.006024459304777396% of the total data.
Partial Unexpected List: Values ​​that do not match expectations are "0".
Missing Count and Percent: There are no missing values ​​in the 'platform' column.
From these results, it can be concluded that overall, the 'platform' column has met expectations well. There is only 1 value that does not match the set of expected values, but the percentage is very small (less than 1%).

To handle the value "0" that does not match expectations, further investigation can be carried out to understand the meaning and context of this value in the dataset. If necessary, these values ​​can be considered for removal or replacement with more appropriate values.



The reason for using Expectation `Contain` in the platform column is to ensure that the values ​​in the 'platform' column only contain the expected video game platform, such as 'PS4', 'Xbox One', 'Nintendo Switch', etc.



### G. Expectation `Missing Value` pada kolom Video Game Sales Report

In [9]:
# Expectation 7 : Column `year` can not contain missing values

validator.expect_column_values_to_not_be_null('year')

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 16599,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": []
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

Insight for the result The 'year' column does not contain NULL/missing values.
All data rows in the dataset have complete year values.
The expectation that the 'year' column should not contain NULL/missing values ​​has been met.
This shows that this dataset has good data completeness and quality in the 'year' column. There are no problems regarding the availability of year data in this dataset.

The reason for using Expectation `Missing Value` in the year column is that it can detect data errors where if there is a row of data that has an invalid or inappropriate year value, the Expectation `Missing Value' will mark this as "missing value"